name: Build Raspberry Pi Pico UF2

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
  workflow_dispatch:  # Добавляет возможность ручного запуска

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up dependencies
        run: |
          sudo apt update
          sudo apt install -y cmake gcc-arm-none-eabi build-essential ninja-build

      - name: Clone Pico SDK
        run: |
          git clone --depth=1 https://github.com/raspberrypi/pico-sdk.git
          echo "PICO_SDK_PATH=$GITHUB_WORKSPACE/pico-sdk" >> $GITHUB_ENV

      - name: Configure and build project
        run: |
          mkdir -p build
          cd build
          cmake .. -DPICO_SDK_PATH=$PICO_SDK_PATH
          make -j$(nproc)

      - name: Upload UF2 artifact
        uses: actions/upload-artifact@v4
        with:
          name: pico-firmware
          path: build/*.uf2
